// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	Void
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/wzhliang/xing"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting string `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*Void)(nil), "Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option

// Client API for Greeter service

type GreeterClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
	Nihao(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*Void, error)
}

type greeterClient struct {
	c           *client.Client
	serviceName string
}

func NewGreeterClient(serviceName string, c *client.Client) GreeterClient {
	if len(serviceName) == 0 {
		serviceName = "greeter"
	}
	RegisterGreeterHandler(c, &Greeter{})
	return &greeterClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *greeterClient) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	_, out, err := c.c.Call(ctx, c.serviceName, "Hello", in, true)
	if out == nil {
		return nil, err
	}
	v := out.(*HelloResponse)
	return v, err
}

func (c *greeterClient) Nihao(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*Void, error) {
	_, _, err := c.c.Call(ctx, c.serviceName, "Nihao", in, false)
	return nil, err
}

// Server API for Greeter service

type GreeterHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
	Nihao(context.Context, *HelloRequest, *Void) error
}

func RegisterGreeterHandler(s *client.Client, hdlr GreeterHandler) {
	s.NewHandler(hdlr)
}

type Greeter struct {
	GreeterHandler
}

func (h *Greeter) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.GreeterHandler.Hello(ctx, in, out)
}

func (h *Greeter) Nihao(ctx context.Context, in *HelloRequest, out *Void) error {
	return h.GreeterHandler.Nihao(ctx, in, out)
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0xf1, 0x00, 0x71, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x6d, 0x2e, 0x5e, 0xa8, 0x9a, 0xe2, 0x82, 0xfc, 0xbc,
	0xe2, 0x54, 0x21, 0x29, 0x2e, 0x8e, 0xf4, 0xa2, 0xd4, 0xd4, 0x92, 0xcc, 0xbc, 0x74, 0x09, 0x26,
	0xb0, 0x42, 0x38, 0x5f, 0x89, 0x8d, 0x8b, 0x25, 0x2c, 0x3f, 0x33, 0xc5, 0x28, 0x84, 0x8b, 0xdd,
	0x1d, 0x24, 0x96, 0x5a, 0x24, 0xa4, 0xc1, 0xc5, 0x0a, 0xd6, 0x2f, 0xc4, 0xab, 0x87, 0x6c, 0x97,
	0x14, 0x9f, 0x1e, 0x8a, 0xb1, 0x4a, 0x0c, 0x42, 0xf2, 0x5c, 0xac, 0x7e, 0x99, 0x19, 0x89, 0x18,
	0x2a, 0x59, 0xf5, 0x40, 0x66, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x5d, 0x6d, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x1a, 0x06, 0x9d, 0xc4, 0x00, 0x00, 0x00,
}
